name: 'android-lint-action'
description: 'Reports Android Lint issues using reviewdog'
author: 'Ilya Gulya'
branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  github_token:
    description: 'GITHUB_TOKEN to use for reviewdog'
    required: false
    default: {{ github.token }}
  lint_xml_file:
    description: 'Path to the Android Lint XML result file'
    required: true
  reporter:
    description: 'Reporter of reviewdog [github-pr-check,github-pr-review,github-check]'
    required: false
    default: 'github-pr-check'
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    required: false
    default: 'warning'
  reviewdog_flags:
    description: 'Additional reviewdog flags'
    required: false
    default: ''

runs:
  using: 'node20'
  main: 'dist/index.js'
